jobs:
  include:
    - language: node_js
      node_js: 12
      if: branch = master
      script:
        - cd ts
        - npm install
        - npm run test-cov
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF node_js
    - language: go
      go: 1.12.x
      install:
        - export GO111MODULE=on 
      if: branch = master
      script:
        - cd golang
        - go mod tidy
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./service/... ./utils...
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF go
    - language: go
      go: 1.13.x
      install:
        - export GO111MODULE=on 
      if: branch = master
      script:
        - cd golang
        - go mod tidy
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./service/... ./utils...
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF go  
    - language: go
      go: 1.14.x
      install:
        - export GO111MODULE=on 
      if: branch = master
      script:
        - cd golang
        - go mod tidy
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./service/... ./utils...
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF go
    - language: go
      go: 1.15.x
      install:
        - export GO111MODULE=on 
      if: branch = master
      script:
        - cd golang
        - go mod tidy
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./service/... ./utils...
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF go         
    - language: java
      jdk: openjdk8
      if: branch = master
      script:
        - cd java
        - mvn test -B
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF java
    - language: csharp
      mono: none
      dist: xenial
      branches:
        only:
          - master
      before_install:
        - wget https://download.visualstudio.microsoft.com/download/pr/42f39f2f-3f24-4340-8c57-0a3133620c21/0a353696275b00cbddc9f60069867cfc/dotnet-sdk-2.2.110-linux-x64.tar.gz
        - mkdir -p ~/dotnet/ && tar zxf dotnet-sdk-2.2.110-linux-x64.tar.gz -C ~/dotnet/
        - sudo ln -sf ~/dotnet/dotnet /usr/bin/dotnet
        - dotnet --info
      install:
        - cd csharp/tests
        - dotnet tool install --global altcover.visualizer
        - dotnet restore
        - dotnet build
        - cd ../
      script:
        - dotnet test tests/ /p:AltCover=true
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF csharp
    - language: python
      python:
        - "3.6"
      env:
        - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
      install:
        - pip install coverage
        - pip install alibabacloud-tea
      script:
        - cd python
        - coverage run --source=alibabacloud_apigateway_util -m pytest tests/test_*
        - wget --no-check-certificate https://codecov.io/bash -O codecov.sh
        - bash codecov.sh -cF "python"